const { REASON_CLASS, REASON_ACTION } = require("./reason_enums");

const MAP = {
"BLEND_FILE_NOT_FOUND": {
class: REASON_CLASS.BLEND_FILE_NOT_FOUND,
action: REASON_ACTION.FIX_AND_RESUBMIT,
details: "Blend file not found"
},
"BLENDER_PRECHECK_FAILED": {
class: REASON_CLASS.PRECHECK_FAILED,
action: REASON_ACTION.FIX_AND_RESUBMIT,
details: "Blender precheck failed"
},
"PRECHECK_OUTPUT_PARSE_ERROR": {
class: REASON_CLASS.PRECHECK_FAILED,
action: REASON_ACTION.FIX_AND_RESUBMIT,
details: "Precheck output could not be parsed"
},
"PRESET_VIOLATION:MEM:BUDGET": {
class: REASON_CLASS.MEMORY_BUDGET_EXCEEDED,
action: REASON_ACTION.CHOOSE_MORE_FLEXIBLE_PROFILE
},
"PRESET_VIOLATION:GEOM:SIZE": {
class: REASON_CLASS.GEOMETRY_TOO_LARGE,
action: REASON_ACTION.REDUCE_GEOMETRY
},
"PRESET_VIOLATION:VERSION:UNSUPPORTED": {
class: REASON_CLASS.UNSUPPORTED_VERSION,
action: REASON_ACTION.USE_SUPPORTED_VERSION
},
"RENDER_CRASH:UNKNOWN": {
class: REASON_CLASS.RENDER_FAILURE,
action: REASON_ACTION.NONE
},
"BLENDER_CRASH": {
class: REASON_CLASS.RENDER_FAILURE,
action: REASON_ACTION.NONE
},
"WORKER_ERROR:TIMEOUT": {
class: REASON_CLASS.RUNTIME_WINDOW_EXCEEDED,
action: REASON_ACTION.CHOOSE_MORE_FLEXIBLE_PROFILE
},
"WORKER_ERROR:UNKNOWN": {
class: REASON_CLASS.UNKNOWN_FAILURE,
action: REASON_ACTION.NONE
}
};

module.exports = MAP;