const REASON_CLASS = {
BLEND_FILE_NOT_FOUND: "BLEND_FILE_NOT_FOUND",
PRECHECK_FAILED: "PRECHECK_FAILED",
UNSUPPORTED_VERSION: "UNSUPPORTED_VERSION",
INVALID_PROJECT_STRUCTURE: "INVALID_PROJECT_STRUCTURE",
UNSUPPORTED_NODES: "UNSUPPORTED_NODES",
MEMORY_BUDGET_EXCEEDED: "MEMORY_BUDGET_EXCEEDED",
GEOMETRY_TOO_LARGE: "GEOMETRY_TOO_LARGE",
RUNTIME_WINDOW_EXCEEDED: "RUNTIME_WINDOW_EXCEEDED",
RENDER_FAILURE: "RENDER_FAILURE",
UNKNOWN_FAILURE: "UNKNOWN_FAILURE"
};

const REASON_ACTION = {
FIX_AND_RESUBMIT: "FIX_AND_RESUBMIT",
USE_SUPPORTED_VERSION: "USE_SUPPORTED_VERSION",
REDUCE_MEMORY_USAGE: "REDUCE_MEMORY_USAGE",
REDUCE_GEOMETRY: "REDUCE_GEOMETRY",
SIMPLIFY_MATERIALS: "SIMPLIFY_MATERIALS",
CHOOSE_MORE_FLEXIBLE_PROFILE: "CHOOSE_MORE_FLEXIBLE_PROFILE",
NONE: "NONE"
};

module.exports = { REASON_CLASS, REASON_ACTION };